# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: GateofBabylon
email: l470279614@yahoo.com
description:  博客转移到 http://45.77.13.75:1234/ 欢迎访问
baseurl: "/GateofBabylon" # the subpath of your site, e.g. /blog
#url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: Loon
github_username:  Loon

# Build settings

markdown: kramdown

